import com.google.gson.JsonElement
import com.google.gson.JsonParser
import xyz.wagyourtail.unimined.api.minecraft.task.RemapJarTask

plugins {
    java
    id("xyz.wagyourtail.unimined") version "1.4.1"
    id("com.gradleup.shadow") version "8.+"
    id("com.hypherionmc.modutils.modpublisher") version "2.1.8"
}

base.archivesName.set(project.properties["archives_base_name"] as String)
version = "${project.properties["mod_version"]}+mc${project.properties["minecraft_version"]}"
group = project.properties["maven_group"] as String

unimined.minecraft {
    version(project.properties["minecraft_version"].toString())

    mappings {
        calamus()
        feather(31)

        stubs("searge", "feather") {
            c("net/minecraft/entity/item/EntityMinecart") {
                // fix conflict with forge added function name
                m("func_174898_m;()D", "getMaxSpeedVanilla")
            }
        }

        devNamespace("feather")
    }

    minecraftForge {
        loader(project.properties["forge_version"].toString())
    }

    defaultRemapJar = true
}

val shade: Configuration by configurations.creating

repositories {
    maven { url = uri("https://jitpack.io") }
}

dependencies {
    implementation("com.github.VM-Chinese-translate-group:VMTUCore:${project.properties["core_version"]}")
    shade("com.github.VM-Chinese-translate-group:VMTUCore:${project.properties["core_version"]}")
}

tasks.processResources {
    inputs.property("version", project.version)
    inputs.property("mc_version", project.properties["minecraft_version"])

    filesMatching("mcmod.info") {
        expand(
            mapOf(
                "version" to project.version,
                "mc_version" to project.properties["minecraft_version"]
            )
        )
    }
}

tasks.withType<JavaCompile>().configureEach {
    options.encoding = "UTF-8"
    //options.release = 8
}

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8

    withSourcesJar()
}

tasks.shadowJar {
    //relocate("top.vmctcn.vmtu.core", "vmtu.include.core")

    from(shade)
    archiveClassifier.set("dev-shadow")
}

tasks.named<RemapJarTask>("remapJar") {
    inputFile.set(tasks.shadowJar.get().archiveFile)
    dependsOn(tasks.shadowJar)
    //archiveClassifier.set("")
}

tasks.jar {
    archiveClassifier.set("dev")
}

tasks.processResources.get().dependsOn("convertLanguageFiles")
// Fix implicit dependency: sourcesJar must run after convertLanguageFile
// because sourcesJar includes generated files in src/main/resources
tasks.named("sourcesJar").get().dependsOn("convertLanguageFiles")

// JSON to Lang file gradle task
tasks.register("convertLanguageFiles") {
    description = "Convert JSON language files to Minecraft *.lang format"

    val inputDir = file("scripts/inputs")
    val outputDir = file("src/main/resources/assets/vmtranslationupdate/lang")

    inputs.dir(inputDir)
    outputs.dir(outputDir)

    doLast {
        // Ensure output directory exists
        outputDir.mkdirs()

        // Get all JSON files
        val jsonFiles = inputDir.listFiles { file ->
            file.isFile && file.extension.equals("json", ignoreCase = true)
        } ?: emptyArray()

        if (jsonFiles.isEmpty()) {
            logger.warn("⚠️ No JSON files found in ${inputDir.absolutePath}")
            return@doLast
        }

        logger.lifecycle("♻️ Starting conversion of ${jsonFiles.size} JSON file(s)...")

        jsonFiles.forEach { jsonFile ->
            val langFileName = jsonFile.nameWithoutExtension + ".lang"
            val langFile = File(outputDir, langFileName)

            try {
                // Read and parse JSON
                val jsonContent = jsonFile.readText(Charsets.UTF_8)
                val jsonElement = JsonParser.parseString(jsonContent)

                if (!jsonElement.isJsonObject) {
                    throw IllegalArgumentException("JSON file must contain an object: ${jsonFile.name}")
                }

                val jsonObject = jsonElement.asJsonObject

                // Flatten nested JSON and convert to lang format
                val langLines = mutableListOf<String>()
                langLines.add("# This file is auto-generated by Gradle task")
                langLines.add("# Please modify with caution")
                langLines.add("")

                // Recursively flatten JSON object
                fun flattenJson(element: JsonElement, parentKey: String = "") {
                    when {
                        element.isJsonObject -> {
                            element.asJsonObject.entrySet().forEach { (key, value) ->
                                val newKey = if (parentKey.isEmpty()) key else "$parentKey.$key"
                                flattenJson(value, newKey)
                            }
                        }
                        element.isJsonPrimitive -> {
                            val primitive = element.asJsonPrimitive
                            val value = when {
                                primitive.isBoolean -> primitive.asBoolean.toString()
                                primitive.isNumber -> primitive.asNumber.toString()
                                else -> primitive.asString
                            }
                            langLines.add("$parentKey=$value")
                        }
                        element.isJsonArray -> {
                            // Serialize array to JSON string
                            langLines.add("$parentKey=${element.toString()}")
                        }
                        element.isJsonNull -> {
                            langLines.add("$parentKey=null")
                        }
                    }
                }

                flattenJson(jsonObject)

                // Write lang file
                langFile.writeText(langLines.joinToString("\n"), Charsets.UTF_8)

                logger.lifecycle("✅ Converted: ${jsonFile.name} -> $langFileName (${langLines.size - 3} key-value pairs)")

            } catch (e: Exception) {
                throw RuntimeException("Failed to convert file ${jsonFile.name}: ${e.message}", e)
            }
        }

        logger.lifecycle("✅ Language file conversion completed! Output directory: ${outputDir.absolutePath}")
    }
}

publisher {
    apiKeys {
        modrinth(System.getenv("MODRINTH_TOKEN"))
        curseforge(System.getenv("CURSEFORGE_TOKEN"))
    }

    curseID = properties["curseforge_id"] as String?
    modrinthID = properties["modrinth_id"] as String?
    versionType = properties["version_type"] as String?
    changelog = rootProject.file("CHANGELOG.md").readText(Charsets.UTF_8)
    projectVersion = "forge-${project.version}"
    displayName = "[Forge]${project.version}"
    gameVersions = listOf(project.properties["minecraft_version"] as String)
    loaders = listOf("forge")
    curseEnvironment = "client"
    artifact = tasks.named("remapJar").get()
//    addAdditionalFile(tasks.named("sourcesJar").get())
}