import com.google.gson.JsonElement
import com.google.gson.JsonParser
import kotlin.collections.component1
import kotlin.collections.component2

plugins {
    id("dev.architectury.mappings-layers-plugin") version "1.4-SNAPSHOT"
    id("com.crystaelix.loom") version "1.13-SNAPSHOT"
    id("ploceus") version "1.15-SNAPSHOT"
    id("maven-publish")
    id("com.hypherionmc.modutils.modpublisher") version "2.+"
    id("com.gradleup.shadow") version "8.+"
}

val modVersion = project.properties["mod_version"] as String
val modGroup = project.properties["maven_group"] as String
val modArchiveBaseName = project.properties["archives_base_name"] as String
val modId = project.properties["mod_id"] as String
val modAuthor = project.properties["mod_author"] as String
val mappingsVersion = project.properties["mappings_version"] as String
val minecraftVersion = project.properties["minecraft_version"] as String
val forgeVersion = project.properties["forge_version"] as String
val curseforgeId = project.properties["curseforge_id"] as String
val modrinthId = project.properties["modrinth_id"] as String
val versionType = project.properties["version_type"] as String

version = "${modVersion}+mc${minecraftVersion}"
group = modGroup
base.archivesName.set(modArchiveBaseName)

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8

    withSourcesJar()
}

tasks.withType<JavaCompile> {
    options.encoding = "UTF-8"
}

loom {
    silentMojangMappingsLicense()

    //generatedIntermediateMappings()
}

val shade: Configuration by configurations.creating

repositories {
    mavenLocal()
    mavenCentral()
    maven { url = uri("https://jitpack.io") }
}

dependencies {
    // Minecraft dependencies, required
    minecraft("com.mojang:minecraft:${minecraftVersion}")
    mappings(mappingsLayers.from(ploceus.featherMappings(mappingsVersion)) {
        mapMethod("m_9076954", "getMaxSpeedVanilla")
    })
    legacyForge("net.minecraftforge:forge:${minecraftVersion}-${forgeVersion}")

    implementation("com.github.VM-Chinese-translate-group:VMTUCore:0.3.1")
    include("com.github.VM-Chinese-translate-group:VMTUCore:0.3.1")
}

tasks.processResources {
    filteringCharset = "UTF-8"
    filesMatching("mcmod.info") {
        expand(mapOf(
            "mod_id" to modId,
            "mod_name" to base.archivesName.get(),
            "mod_version" to project.version
        ))
    }
}

val manifestAttributes = mapOf(
    "Specification-Title" to modArchiveBaseName,
    "Specification-Vendor" to modAuthor,
    "Specification-Version" to "1",
    "Implementation-Title" to base.archivesName.get(),
    "Implementation-Version" to project.version,
    "Implementation-Vendor" to modAuthor,
)

tasks.shadowJar {
    from(shade)
    archiveClassifier.set("dev-shadow")
}

tasks.remapJar {
    inputFile.set(tasks.shadowJar.get().archiveFile)
    dependsOn(tasks.shadowJar)
}

tasks.jar {
    manifest.attributes(manifestAttributes)
}

tasks.named<Jar>("sourcesJar") {
    manifest.attributes(manifestAttributes)
}

tasks.processResources.get().dependsOn("convertLanguageFiles")
tasks.processTestResources.get().dependsOn("convertLanguageFiles")
tasks.named("sourcesJar").get().dependsOn("convertLanguageFiles")

tasks.register("convertLanguageFiles") {
    description = "Convert JSON language files to Minecraft *.lang format"

    val inputDir = file("scripts/langs")
    val outputDir = file("src/main/resources/assets/vmtranslationupdate/lang")

    inputs.dir(inputDir)
    outputs.dir(outputDir)

    doLast {
        // Ensure output directory exists
        outputDir.mkdirs()

        // Get all JSON files
        val jsonFiles = inputDir.listFiles { file ->
            file.isFile && file.extension.equals("json", ignoreCase = true)
        } ?: emptyArray()

        if (jsonFiles.isEmpty()) {
            logger.warn("⚠️ No JSON files found in ${inputDir.absolutePath}")
            return@doLast
        }

        logger.lifecycle("♻️ Starting conversion of ${jsonFiles.size} JSON file(s)...")

        jsonFiles.forEach { jsonFile ->
            val langFileName = jsonFile.nameWithoutExtension + ".lang"
            val langFile = File(outputDir, langFileName)

            try {
                // Read and parse JSON
                val jsonContent = jsonFile.readText(Charsets.UTF_8)
                val jsonElement = JsonParser.parseString(jsonContent)

                if (!jsonElement.isJsonObject) {
                    throw IllegalArgumentException("JSON file must contain an object: ${jsonFile.name}")
                }

                val jsonObject = jsonElement.asJsonObject

                // Flatten nested JSON and convert to lang format
                val langLines = mutableListOf<String>()
                langLines.add("# This file is auto-generated by Gradle task")
                langLines.add("# Please modify with caution")
                langLines.add("")

                // Recursively flatten JSON object
                fun flattenJson(element: JsonElement, parentKey: String = "") {
                    when {
                        element.isJsonObject -> {
                            element.asJsonObject.entrySet().forEach { (key, value) ->
                                val newKey = if (parentKey.isEmpty()) key else "$parentKey.$key"
                                flattenJson(value, newKey)
                            }
                        }
                        element.isJsonPrimitive -> {
                            val primitive = element.asJsonPrimitive
                            val value = when {
                                primitive.isBoolean -> primitive.asBoolean.toString()
                                primitive.isNumber -> primitive.asNumber.toString()
                                else -> primitive.asString
                            }
                            langLines.add("$parentKey=$value")
                        }
                        element.isJsonArray -> {
                            // Serialize array to JSON string
                            langLines.add("$parentKey=$element")
                        }
                        element.isJsonNull -> {
                            langLines.add("$parentKey=null")
                        }
                    }
                }

                flattenJson(jsonObject)

                // Write lang file
                langFile.writeText(langLines.joinToString("\n"), Charsets.UTF_8)

                logger.lifecycle("✅ Converted: ${jsonFile.name} -> $langFileName (${langLines.size - 3} key-value pairs)")

            } catch (e: Exception) {
                throw RuntimeException("Failed to convert file ${jsonFile.name}: ${e.message}", e)
            }
        }

        logger.lifecycle("✅ Language file conversion completed! Output directory: ${outputDir.absolutePath}")
    }
}

publisher {
    apiKeys {
        modrinth(System.getenv("MODRINTH_TOKEN"))
        curseforge(System.getenv("CURSEFORGE_TOKEN"))
    }

    curseID = curseforgeId
    modrinthID = modrinthId
    versionType = versionType
    changelog = rootProject.file("CHANGELOG.md").readText(Charsets.UTF_8)
    projectVersion = "forge-${project.version}"
    displayName = "[Forge] ${project.version}"
    gameVersions = listOf(project.properties["minecraft_version"] as String)
    loaders = listOf("forge")
    curseEnvironment = "client"
    artifact = tasks.remapJar.get()
    addAdditionalFile(tasks.remapSourcesJar.get())
}