org.gradle.jvmargs=-Xmx2048M

minecraft_version=1.21.7
enabled_platforms=fabric,neoforge
yarn_mappings=1.21.7+build.8
yarn_patch=1.21+build.4

archives_base_name=VMTranslationUpdate
mod_version=3.2.1
maven_group=top.vmctcn.vmtranslationupdate

clothconfig_version=19.0.147

fabric_loader_version=0.16.14
fabric_api_version=0.129.0+1.21.7
modmenu_version=15.0.0-beta.3

neoforge_version=21.7.25-beta

core_version=0.1.1