org.gradle.jvmargs=-Xmx2048M

minecraft_version=1.21.11
enabled_platforms=fabric,neoforge

archives_base_name=VMTranslationUpdate
mod_version=4.1.0
maven_group=top.vmctcn.vmtranslationupdate

clothconfig_version=21.11.153

fabric_loader_version=0.18.4
fabric_api_version=0.140.2+1.21.11
modmenu_version=17.0.0-beta.1

neoforge_version=21.11.14-beta

core_version=0.2.16
