org.gradle.jvmargs=-Xmx2048M

minecraft_version=1.21.10
enabled_platforms=fabric,neoforge
yarn_mappings=1.21.10+build.2
yarn_patch=1.21+build.4

archives_base_name=VMTranslationUpdate
mod_version=4.1.0
maven_group=top.vmctcn.vmtranslationupdate

clothconfig_version=20.0.149

fabric_loader_version=0.17.3
fabric_api_version=0.136.0+1.21.10
modmenu_version=16.0.0-rc.1

neoforge_version=21.10.40-beta

core_version=0.2.13
