plugins {
    id("dev.kikugie.stonecutter")
    id("dev.architectury.loom") version "1.13-SNAPSHOT" apply false
    id("architectury-plugin") version "3.4-SNAPSHOT" apply false
    id("com.gradleup.shadow") version "9.3.1" apply false
    id("com.hypherionmc.modutils.modpublisher") version "2.1.8" apply false
}

stonecutter active file("versions/currentVersion") /* [SC] DO NOT EDIT THIS FILE */

// Runs currentVersion versions for each loader
for (it in stonecutter.tree.nodes) {
    if (it.metadata != stonecutter.current || it.branch.id.isEmpty()) continue
    val types = listOf("Client", "Server")
    val loader = it.branch.id.upperCaseFirst()
    for (type in types) tasks.register("runActive$type$loader") {
        group = "project"
        dependsOn("${it.hierarchy}run$type")
    }
}

stonecutter parameters {
    replacements.string(current.parsed >= "1.21.11") {
        //replace("ResourceLocation", "Identifier")
        replace("net.minecraft.Util", "net.minecraft.util.Util")
    }
}
