modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/VM-Chinese-translate-group/VMTranslationUpdateMod/issues"
license = "MIT"

[[mods]]
modId = "vmtranslationupdate"
version = "${version}"
displayName = "VM Translation Update"
displayURL = "https://github.com/VM-Chinese-translate-group/VMTranslationUpdateMod"
authors = "Wulian233, TexTrue, Litchiiiiiii"
description = '''
A mod for checking for updates to VM Chinese Group's localization patches
and automatically downloading resource packs.
'''
logoFile = "icon.png"

[[dependencies.vmtranslationupdate]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vmtranslationupdate]]
modId = "cloth_config"
type = "required"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"