modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/VM-Chinese-translate-group/VMTranslationUpdateMod/issues"
license = "MIT"

[[mods]]
modId = "vmtranslationupdate"
version = "${version}"
displayName = "VM Translation Update"
displayURL = "https://vmct-cn.top/vmtu"
authors = "Wulian233, TexTrue"
description = '''
The VM Chinese translate Group mod is used to check Chinese localization patches and some other utility features.
'''
logoFile = "assets/vmtranslationupdate/icon.png"

[[mixins]]
config = "vmtranslationupdate.mixins.json"

[[dependencies.vmtranslationupdate]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.6,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vmtranslationupdate]]
modId = "cloth_config"
type = "required"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"