modLoader = "javafml"
loaderVersion = "[20,)"
issueTrackerURL = "https://github.com/VM-Chinese-translate-group/VMTranslationUpdateMod/issues"
license = "MIT"

[[mods]]
modId = "vmtranslationupdate"
version = "${version}"
displayName = "VM Translation Update"
displayURL = "https://github.com/VM-Chinese-translate-group/VMTranslationUpdateMod"
authors = "Wulian233, TexTrue, Litchiiiiiii"
description = '''
The VM Chinese translate Group mod is used to check Chinese localization patches and some other utility features.
'''
logoFile = "assets/vmtranslationupdate/icon.png"

[[dependencies.vmtranslationupdate]]
modId = "neoforge"
type = "required"
versionRange = "[20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vmtranslationupdate]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.5,1.20.6]"
ordering = "NONE"
side = "BOTH"

[[dependencies.vmtranslationupdate]]
modId = "cloth_config"
type = "required"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"