name: Build

on: [ pull_request, push, workflow_dispatch ]

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            .gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', 'build.gradle') }}
      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew build

      - name: Merge Fabric & Forge & NeoForge JARs
        run: |
          chmod +x gradlew
          ./gradlew fusejars

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: |
            ${{ github.workspace }}/fabric/build/libs
            ${{ github.workspace }}/forge/build/libs
            ${{ github.workspace }}/neoforge/build/libs
            ${{ github.workspace }}/build/merged